version: '3.8'

services:
  redis:
    container_name: node-redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker

  # note-web:
  #   build: ./web/
  #   container_name: node-web
  #   image: note-web:1.0
  #   ports:
  #     - "4000:3000"
  #   depends_on:
  #     - note-api
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:4000/api

  note-api:
    container_name: node-api
    build: ./api/
    image: note-api:1.0
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
  
  nginx:
    build: ./nginx/
    container_name: node-nginx
    ports:
      - "3000:3000"
    depends_on:
      - note-api
