@baseUrl = http://localhost:8080/api

POST {{baseUrl}}/records
content-type: application/json

{
    "message": "testes"
}

###

get {{baseUrl}}/records/b86e827d-59cc-4980-a9e7-6019da15fe64
content-type: application/json

###

get {{baseUrl}}/records
content-type: application/json

###

PATCH {{baseUrl}}/records/b86e827d-59cc-4980-a9e7-6019da15fe64
content-type: application/json

{
    "message": "mesnagem alterada"
}

###

DELETE  {{baseUrl}}/records/b86e827d-59cc-4980-a9e7-6019da15fe64
content-type: application/json

###

POST {{baseUrl}}/files/upload
Content-Disposition: form-data; name=teste.txt; filename=/home/andre/Desktop/teste.txt
Content-Type: multipart/form-data; 

### 

GET {{baseUrl}}/files/download/1796ede2-666b-48ec-a86e-6fbf4d66fef1
Content-Type: application/javascript