
POST http://localhost:4000/api/message
Content-Type: application/json

{
    "message" : "teste de mensagem alterada"
}

###

PUT  http://localhost:4000/api/message/ab977cc9-2e81-4824-9849-4a182f68e3df
Content-Type: application/json

{
    "message" : "mensagem alterada"
}

### 

GET  http://localhost:4000/api/message/ab977cc9-2e81-4824-9849-4a182f68e3df